package com.workout.jetpack_workout.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xff67be70) // accent
val md_theme_light_onPrimary = Color(0xffffffff) // text filled button
val md_theme_light_primaryContainer = Color(0xffffffff) // card background
val md_theme_light_onPrimaryContainer = Color(0xff000000) // main text
val md_theme_light_secondary = Color(0x2667be70) // tinted button
val md_theme_light_onSecondary = Color(0xff67be70) // accent
val md_theme_light_secondaryContainer = Color(0xffffffff) // card background
val md_theme_light_onSecondaryContainer = Color(0xff000000) // main text
val md_theme_light_tertiary = Color(0xff67be70) // accent
val md_theme_light_onTertiary = Color(0xffffffff) // text filled button
val md_theme_light_tertiaryContainer = Color(0xffffffff) // card background
val md_theme_light_onTertiaryContainer = Color(0xff000000) // main text
val md_theme_light_error = Color(0xffe14b4b) // error
val md_theme_light_errorContainer = Color(0xffffffff) // background
val md_theme_light_onError = Color(0xffffffff) // text filled button
val md_theme_light_onErrorContainer = Color(0xff000000) // main text
val md_theme_light_background = Color(0xffffffff) // background
val md_theme_light_onBackground = Color(0xff000000) // main text
val md_theme_light_surface = Color(0xffffffff) // background
val md_theme_light_onSurface = Color(0xff000000) // main text
val md_theme_light_surfaceVariant = Color(0xffffffff) // background
val md_theme_light_onSurfaceVariant = Color(0xff858383) // small elements
val md_theme_light_outline = Color(0x66858383) // separators
val md_theme_light_inverseOnSurface = Color(0xffffffff) // background
val md_theme_light_inverseSurface = Color(0xff000000) // main text
val md_theme_light_inversePrimary = Color(0xffffffff) // background
val md_theme_light_outlineVariant = Color(0x66858383) // separators
val md_theme_light_scrim = Color(0xff000000) // main text

val md_theme_dark_primary = Color(0xff6ac173)  // accent
val md_theme_dark_onPrimary = Color(0xff1a1a1a) // text filled button
val md_theme_dark_primaryContainer = Color(0xff2e3034)  // card background
val md_theme_dark_onPrimaryContainer = Color(0xffffffff)  // main text
val md_theme_dark_secondary = Color(0x1f6ac173)  // tinted button
val md_theme_dark_onSecondary = Color(0xff6ac173)  // accent
val md_theme_dark_secondaryContainer = Color(0xff2e3034)  // card background
val md_theme_dark_onSecondaryContainer = Color(0xffffffff)  // main text
val md_theme_dark_tertiary = Color(0xff6ac173)  // accent
val md_theme_dark_onTertiary = Color(0xff1a1a1a) // text filled button
val md_theme_dark_tertiaryContainer = Color(0xff2e3034)  // card background
val md_theme_dark_onTertiaryContainer = Color(0xffffffff)  // main text
val md_theme_dark_error = Color(0xffe95353) // error
val md_theme_dark_errorContainer = Color(0xff1a1a1a) // background
val md_theme_dark_onError = Color(0xff1a1a1a) // text filled button
val md_theme_dark_onErrorContainer = Color(0xffffffff)  // main text
val md_theme_dark_background = Color(0xff1a1a1a) // background
val md_theme_dark_onBackground = Color(0xffffffff)  // main text
val md_theme_dark_surface = Color(0xff1a1a1a) // background
val md_theme_dark_onSurface = Color(0xffffffff)  // main text
val md_theme_dark_surfaceVariant = Color(0xff1a1a1a) // background
val md_theme_dark_onSurfaceVariant = Color(0xffb5bcbc) // small elements
val md_theme_dark_outline = Color(0x80959595) // separators
val md_theme_dark_inverseOnSurface = Color(0xff1a1a1a) // background
val md_theme_dark_inverseSurface = Color(0xffffffff)  // main text
val md_theme_dark_inversePrimary = Color(0xff1a1a1a) // background
val md_theme_dark_outlineVariant = Color(0x80959595) // separators
val md_theme_dark_scrim = Color(0xffffffff)  // main text